[package]
name = "escjson_func"
version = "0.1.0"
edition = "2024"

[lib]
name = "escjson_func"
path = "src/lib.rs"

[dependencies]
libc = { workspace = true }
gandiva_rust_udf_macro = { workspace = true }
gandiva_rust_udf_shared = { workspace = true }
serde_json = "1.0.95"
