name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install gandiva_rust_udf_build
        run: cargo install gandiva_rust_udf_build

      - name: Run tests
        run: gen-udf-reg && cargo test --workspace --verbose
